se completa la ruta cart
PatricioLabra/ProyectoWEB pull request #29
Opened 2021-06-18 05:29 UTC by PatricioLabra

Realicé unas configuraciones iniciales de la ruta. Pero, no e podido subir los datos a la BD como para ir testeandolos de ahí. 
Supongo que es porque la colección tiene el nombre ShoppingCartsBought y no de Carts. Quería tratar de cambiarle el nombre, pero me dió cosita hacerlo. No queria mandarme algún cagazo.

2021-06-18 05:30 UTC, PatricioLabra commented
Espero tu retroalimentación y comentarios para seguir trabajando con esta ruta.

2021-06-18 15:54 UTC, DanRivaille requested changes
Te deje un par de comentarios

2021-06-18 15:54 UTC, DanRivaille commented on backend/src/routes/cart/cart.controller.ts
> +    return res.status(200).send({ success: true });
Se podria retornar cartSaved, quizas no se utilice, pero para que este ahi

2021-06-18 15:54 UTC, DanRivaille commented on backend/src/routes/cart/cart.routes.ts
> +export default router;
Salto de linea al final

2021-06-18 15:54 UTC, DanRivaille commented on backend/src/routes/cart/cart.controller.ts
> +    const newCart = {nickname_buyer, products};
Crea una funcion destructureProducts() que extraiga solo la informacion que se va a guardar en la bd

2021-06-18 15:54 UTC, DanRivaille commented on backend/src/routes/cart/cart.model.ts
> +    products:Schema.Types.Mixed
products: [Schema.Types.Mixed]

2021-06-18 15:57 UTC, PatricioLabra commented on backend/src/routes/cart/cart.controller.ts
> +    return res.status(200).send({ success: true });
perfecto

2021-06-18 15:57 UTC, PatricioLabra commented on backend/src/routes/cart/cart.routes.ts
> +export default router;
recibido

2021-06-18 15:58 UTC, PatricioLabra commented on backend/src/routes/cart/cart.controller.ts
> +    const newCart = {nickname_buyer, products};
okay chaval

2021-06-18 16:15 UTC, PatricioLabra commented on backend/src/routes/cart/cart.controller.ts
> +    const newCart = {nickname_buyer, products};
mmm.. es decir, que los datos de los productos comprados los obtengo desde el endpoint y no son ingresados? entonces, necesitaría que me ingresen id_product, quantity y nickname_buyer solamente.

2021-06-18 19:02 UTC, DanRivaille commented on backend/src/routes/cart/cart.controller.ts
> +    const newCart = {nickname_buyer, products};
No, es que carrito en el front tiene un par de atributos extras
`ProductCart {
  _id: string;
  name: string;
  price: number;
  quantity: number;
  discount: number;
  image_url: string;
  stock: number; //No se guarda
  finalPrice:number; //tampoco se guarda
`
entonces para que no se guarden en la DB

2021-06-18 23:55 UTC, PatricioLabra commented
Ahora si:
- se almacenan los carritos en la BD:
![imagen](https://user-images.githubusercontent.com/39105967/122624230-34c0df00-d06d-11eb-8b84-371bbbe151d5.png)

- getNewerCarts y getCart retornan los carritos con información publica. Le dejé el id_product, pero se lo puedo sacar si quieres:
![imagen](https://user-images.githubusercontent.com/39105967/122624335-bf094300-d06d-11eb-811e-c1953d8d89f2.png)
![imagen](https://user-images.githubusercontent.com/39105967/122624569-bd8c4a80-d06e-11eb-96e5-34111aa7a93f.png)
![imagen](https://user-images.githubusercontent.com/39105967/122624522-86b63480-d06e-11eb-801f-1d71b9f69425.png)

- tambien se agregaron las modificaciones sugeridas 
![imagen](https://user-images.githubusercontent.com/39105967/122624613-f5938d80-d06e-11eb-9bdc-d309d69569e2.png)
![imagen](https://user-images.githubusercontent.com/39105967/122624620-00e6b900-d06f-11eb-8d9e-db216daccd71.png)

2021-06-19 00:26 UTC, DanRivaille approved these changes
Esta excelente

2021-06-19 00:27 UTC, merged